spring:
  application:
    name: server
  profiles:
    include: local

# OAuth2
oauth:
  kakao:
    base-url: https://kauth.kakao.com
    app-key: ${OAUTH_KAKAO_APP_KEY}
    public-key-url: /.well-known/jwks.json

# JWT
jwt:
  header: Authorization
  type: Bearer
  issuer: ${ISSUER_NAME}
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

# Sentry
sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
