spring:

# JPA
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

# RDB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_DATASOURCE_ENDPOINT}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}

# Redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

# OAuth2
oauth:
  kakao:
    base-url: https://kauth.kakao.com
    app-key: ${OAUTH_KAKAO_APP_KEY}
    public-key-url: /.well-known/jwks.json

# JWT
jwt:
  header: Authorization
  type: Bearer
  issuer: ${ISSUER_NAME}
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}
